module.exports = {
  siteMetadata: {
    title: 'Tim Roes',
    description: 'Blog of Tim Roes, computer scientist and web enthusiast',
    siteUrl: 'https://www.timroes.de',
    privacyPolicy: 'https://www.iubenda.com/privacy-policy/91999772',
  },
  plugins: [
    'gatsby-plugin-typescript',
    {
      resolve: 'gatsby-plugin-netlify',
      options: {
        headers: {
          '/*': ['Strict-Transport-Security: max-age=31556952; includeSubDomains; preload'],
        },
      },
    },
    'gatsby-plugin-nprogress',
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-plugin-eslint',
      options: {
        test: /\.ts$|\.tsx$|\.js$/,
        stages: ['develop', 'build-javascript'],
        options: {
          failOnWarning: true,
        },
      },
    },
    {
      resolve: 'gatsby-plugin-feed',
      options: {
        feeds: [
          {
            query: `
              {
                allMdx(
                  limit: 1000,
                  sort: {
                    order: DESC,
                    fields: [frontmatter___date]
                  }
                ) {
                  edges {
                    node {
                      frontmatter {
                        title
                        date
                        summary
                      }
                      fields { slug }
                      excerpt
                    }
                  }
                }
              }
            `,
            serialize: ({ query: { site, allMdx } }) =>
              allMdx.edges.map((edge) => ({
                ...edge.node.frontmatter,
                description: edge.node.frontmatter.summary || edge.node.excerpt,
                url: `${site.siteMetadata.siteUrl}/${edge.node.fields.slug}`,
                guid: edge.node.fields.slug,
              })),
            // Where we will save the feed generated by this query.
            output: `rss.xml`,
          },
        ],
      },
    },
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
      },
    },
    'gatsby-plugin-less',
    'gatsby-plugin-sharp',
    'gatsby-plugin-svgr',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'posts',
        path: `${__dirname}/content/posts/`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: `${__dirname}/src/images/`,
      },
    },
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        extensions: ['.md', '.mdx'],
        gatsbyRemarkPlugins: [
          'gatsby-remark-autolink-headers',
          {
            resolve: 'gatsby-remark-images',
            options: {
              // maxWidth: 590,
              withWebp: true,
            },
          },
          {
            resolve: 'gatsby-remark-prismjs',
            options: {
              noInlineHighlight: true,
            },
          },
          'gatsby-remark-external-links',
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-smartypants',
        ],
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-catch-links',
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'UA-112812454-1',
        head: false,
        anonymize: true,
        respectDNT: true,
      },
    },
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'Tim Roes',
        short_name: 'Tim Roes',
        start_url: '/',
        background_color: '#f7f0eb',
        theme_color: '#00705f',
        display: 'minimal-ui',
        icon: 'src/images/logo.png',
      },
    },
    'gatsby-plugin-offline',
  ],
};
